# Imagem Base
FROM python:3.12-slim

WORKDIR /sensor_topic

# Copying necessary files
COPY [".env", "requirements.txt", "sensor_topic/interactive_producer.py", "./"]

# COPY sensor_topic/interactive_producer.py /sensor_topic
# COPY requirements.txt /sensor_topic

# Install dependencies
RUN pip install -r requirements.txt

# Run script
CMD ["python", "interactive_producer.py"]