networks:
  kafka-network:
    name: kafka-network
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - ${ZOOKEEPER_PORT}:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network
  
  kafka:
    image: bitnami/kafka:latest
    restart: on-failure
    ports:
      - "${KAFKA_INTERNAL_PORT}:9092"
      - "${KAFKA_EXTERNAL_PORT}:29092"  # External access from the host
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9093,EXTERNAL://0.0.0.0:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9093,EXTERNAL://localhost:29093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
      - KAFKA_CFG_NUM_PARTITIONS=4
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - kafka-network

####################################### Schema Registry ###################################################
  schema-registry-server:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry-server
    container_name: schema-registry-server
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "${SCHEMA_REGISTRY_PORT}:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-server
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:${KAFKA_INTERNAL_PORT}'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:${SCHEMA_REGISTRY_PORT}
    networks:
      - kafka-network
####################################### Streaming sensor containers  #######################################

  sensor_interactive_producer:
    container_name: sensor_interactive_producer
    build:
      context: .
      dockerfile: Dockerfile.interactive-producer
    # for interactive access
    stdin_open: true
    tty: true
    profiles:
      - interactive
    networks:
      - kafka-network
    depends_on:
      - kafka

  sensor_producer:
    container_name: sensor_producer
    build:
      context: .
      dockerfile: Dockerfile.producer
    profiles:
      - first_interaction
    networks:
      - kafka-network
    depends_on:
      - kafka

  sensor_consumer:
    container_name: sensor_consumer
    build:
      context: .
      dockerfile: Dockerfile.consumer
    profiles:
      - first_interaction
    networks:
      - kafka-network
    depends_on:
      - kafka
  
  second_sensor_consumer:
    container_name: second_sensor_consumer
    build:
      context: .
      dockerfile: Dockerfile.consumer_2
    profiles:
      - new_consumer
    networks:
      - kafka-network
    depends_on:
      - kafka

####################################### Financial Topic #############################
  financial_topic_producer:
    container_name: financial_interactive_consumer
    build:
      context: .
      dockerfile: Dockerfile.schema-registry
    volumes:
      - ./financial_topic:/financial_topic   # ← folder mirroring
    # for interactive access
    stdin_open: true
    tty: true
    profiles:
      - financial
    networks:
      - kafka-network
    depends_on:
      - kafka
      - schema-registry-server
####################################### Conduktor containers  #######################################
  tutorial_postgresql:
    hostname: tutorial_postgresql
    container_name: tutorial_postgresql
    extends:
      service: tutorial_postgresql
      file: conduktor.yml 
            
  tutorial_conduktor-console:
    hostname: tutorial_conduktor-console
    container_name: tutorial_conduktor-console
    extends:
      service: tutorial_conduktor-console
      file: conduktor.yml

volumes:
  pg_data: {}
  conduktor_data: {}
